version: '3.7'
services:
    postgres:
        image: postgres:10.5
        healthcheck:
          test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
          timeout: 45s
          interval: 10s
          retries: 10        
        restart: always
        user: postgres
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - APP_DB_USER=camundauser
          - APP_DB_PASS=camundapass
          - APP_DB_NAME=camunda          
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        volumes: 
          - ./postgres-data:/var/lib/postgresql/data
          # another version
          - ./db:/docker-entrypoint-initdb.d/01-init.sh
          # copy the sql script to create tables          
          - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
          